
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import time
import utils
import numpy as np
import pandas as pd
import scipy

print("--------------------- Starting Process..... ---------------------")
print("--------------------- Loading Data.....  ---------------------")

ratings, portfolio, yield_curve, transition = utils.upload_data()
print(yield_curve)
print("............Loading Data Complete")  
print("-----------------------------------------------------")
print("--------------------- Generating Correlation Matrix  ---------------------")  
port_Cor = utils.Correlation_Matrix(ratings, portfolio)
print("--------------------- Presenting Correlation Matrix  ---------------------")  
print(port_Cor)
P_mrkt  = utils.mkt_value(portfolio)

Total = P_mrkt["Market Value"].sum()

print("--------------------- Generating unique ids ... ---------------------")
P_mrkt["Unique_id"] = np.arange(len(P_mrkt))
print("--------------------- Randomly throwing darts on the wall for Recovering ratings ---------------------")
ratings_w_recov = utils.beta_recovery(ratings)
print("--------------------- Attaching ratings and calculating Spread: Please Wait ... ---------------------")
port_rating = pd.merge(P_mrkt, ratings_w_recov, on="Name")
port2 = utils.time_maturity(port_rating)
y1_now = utils.adjust_yield_curve(port2, yield_curve, time_lead=0)
port2_w_spread = utils.find_comp_spread(port2,y1_now)
print("--------------------- Interpolating Yield Curves.... I think ---------------------")
yc_1yr = utils.adjust_yield_curve(port2_w_spread,yield_curve,time_lead=1)

print("--------------------- Calculating all future outcomes... for 1 year ...---------------------")
Forward_scenarios = utils.one_year_forward(port2_w_spread,transition, yc_1yr)

print("--------------------- Simulating Monte Carlo ... This will take some time ...---------------------")
MC_ratings_sim =  utils.ratings_sim(port2_w_spread,transition,port_Cor,ratings,  N=2000)
print(" Simulating complete! ")
port3 = port2_w_spread.copy()
port3.head()
port3.reset_index(inplace=True)
print("--------------------- Pricing each instrument This will take some time ...---------------------")
MC_result = utils.run_pricing(port3, MC_ratings_sim, Forward_scenarios)
print(" Calculating is finished")
stats = utils.Calculate_Statistics(MC_result,Total)

if __name__ == "__main__":
    print("-------------Available Data (Part 1)------------ ")
    print("~~~~~~~~~~~~~~~Ratings~~~~~~~~~~~~~~~~")
    print(ratings.head())
    print("~~~~~~~~~~~~~~~Portfolio~~~~~~~~~~~~~~~~")
    print(portfolio.head())
    print("~~~~~~~~~~~~~~~Yield Curve~~~~~~~~~~~~~~")
    print(yield_curve.head())
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("~~~~~~~~~~~~~Transition matrix ~~~~~~~~~~~~~")
    print(transition.head())
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")

    print("-------------Step 2  ------------ ")
    print("Below we can see the market values of each instrument.")
    print(P_mrkt["Market Value"].head())
    print("-------------Step 3  ------------ ")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("In the next section we can observe the Possible scenarios. In this case we get different values of Bell's Bonds")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print(Forward_scenarios.head())
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("-------------Step 4  ------------ ")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("This section below shows you a sample simulation of ratings")
    print("~~~~~~~~~~~~~~ Monte Carlo  Ratings ~~~~~~~")
    print(MC_ratings_sim.head())
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("-------------Step 5  ------------ ")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("Proceeding results of the Various Prices Monte Carlo.")
    print(MC_result.head())
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("-------------Step 6  ------------ ")
    print("VAR 95: {} , VAR 99: {} , ES_98: {}, Mean Change: {}, Standard Deviation: {} Initial Port Value: {}".format(*stats))